[package]
name = "touch_controller_plugin_core"
version = "0.1.0"
authors = ["GoogleBen <william.ben.wyatt@gmail.com>"]
edition = "2018"

[lib]
name = "touch_controller_plugin_core"
crate-type = ["cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
serde_json = "1.0"
abi_stable = "0.10"
touch_controller_api = { path = "../touch_controller_api" }